### ISSUE TITLE
yerk.org is returning a 404

### ISSUE THREAD

**Issue by jcushman** [yourcelf/marksism#11]
`https://yerk.org/graphfi/bm.js` seems to be returning a 404.

Maybe consider changing to `https://cdn.rawgit.com/yourcelf/marksism/master/src/graphfi/bm.js`, or something under marks.tirl.org?

**Comment by yourcelf** [comment]
Thanks. I updated the site and bookmarklet to use the rawgit CDN, and fixed yerk.org to redirect to that location so existing bookmarks won't be broken.

**Comment by yourcelf** [comment]
On second thought: rawgit is a poor choice, as it doesn't make updating `bm.js` possible ever (it caches permanently on the first access).  They recommend using a specific tag or commit hash to refer to the file version; but in the case of a bookmarklet, this would require people to update the bookmark any time there's a new commit.

Instead, I'm going to revert to keeping the script somewhere I control, but add a monitoring hook so I get notified if a server conf change ever breaks it again.

**Comment by jcushman** [comment]
Makes sense -- thanks!
