### ISSUE TITLE
GraphFi seems to do nothing ?

### ISSUE THREAD

**Issue by argentcorvid** [yourcelf/marksism#14]
For the past week or so, clicking on GraphFi seems to have no effect. 

Running FireFox Nightly 63a1, tested with no ad or script blocking extensions active. 

I thought it might just be me or Nightly, but I asked around on the MeFi chat and some other people have the same issue.

**Comment by argentcorvid** [comment]
It appears that the Security Certificate for yerk.org is expired as of July 31.

![graphfi certificate error](https://user-images.githubusercontent.com/28569263/43777761-64598dda-9a19-11e8-9fc6-c7d65357576b.jpg)

**Comment by sarahtisdale** [comment]
See discussion here:  https://metatalk.metafilter.com/24886/GraphFi-is-dead-long-live-GraphFi#1311507

Edit your bookmarklet:  replace
    https://yerk.org/graphfi/bm.js
with
    https://cdn.rawgit.com/yourcelf/marksism/master/src/graphfi/bm.js

I'm trying to create a pull request with this change...

**Comment by sarahtisdale** [comment]
Also see issue #11 (https://github.com/yourcelf/marksism/issues/11).

Looks like yourcelf already considered using rawgit to serve the bm.js...

**Comment by yourcelf** [comment]
Apologies for the delay y'all, I was off-grid for 2 weeks.  One of several domains the automated certificate renewal was attempting to renew certificates for on that server had expired, and so the certificate renewal for all of them failed.  That's now fixed, and it should be working from yerk.org again now (though the other alternative hosts from the meta thread are great too).
